---
name: "foo"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  go-stuff:
    name: "Test go stuff (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Configure Go"
        run: .github/workflows/configure_go.sh

      - name: "Cache Go"
        uses: actions/cache@v2
        with:
          path: |  # Cache downloaded Go modules and the GOCACHE (to cache `go run` builds invoked by Makefile)
            ~/go/pkg/mod
            ${{ env.GOCACHE }}
          key: test-${{ runner.os }}-${{ env.GO_VERSION }}-go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: test-${{ runner.os }}-${{ env.GO_VERSION }}-go-

      - name: "Test Go"
        run: |
          env | grep GO
          echo ----
          go env
          go version
