# yamllint --format github .github/workflows/internal-images.yml
---
name: foo

on:
  workflow_dispatch:

jobs:
  # Github Action Runners don't support all operating systems we may need to test. Below ensures
  # we run on the intended minimum platforms. Note: we also use Travis for arm64+ubuntu.
  #
  # Use only images from internal-images.yaml to avoid Docker rate limits and slow install steps.
  test-e2e:
    name: "Run e2e tests via containers (${{ matrix.container }})"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        container: ["ghcr.io/codefromthecrypt/func-e-internal:centos8"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install Go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: "Test"
        run: |
          go version
          uname -a
