---
name: "msi"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  msi:
    name: "Test Windows Installer build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
#          - os: ubuntu-latest
#            setup: sudo apt update -qq && sudo apt install -qq -y osslsigncode
#          - os: macos-latest
#            setup: brew install -q osslsigncode
          - os: windows-latest
            setup: |
              $env:Path += ";C:\msys64\usr\bin"
              pacman -Syu --noconfirm
              pacman -Syy --noconfirm mingw-w64-{i686,x86_64}-osslsigncode --noconfirm

    steps:
      - name: "Try it"
        run: |
          ${{ matrix.setup }}
          which osslsigncode
          osslsigncode --version
