---
name: "msi"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

env:  # echo "mary had a little lamb"|base64
  TETRATELABS_CERT_BASE64: "bWFyeSBoYWQgYSBsaXR0bGUgbGFtYgo="

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  msi:
    name: "Test Windows Installer build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
            # https://packages.ubuntu.com/focal/osslsigncode is old, but apt is less time than brew
            setup: sudo apt update -qq && sudo apt install -qq -y osslsigncode
          - os: macos-latest
            setup: brew install -q osslsigncode
          - os: windows-latest
            setup: |  # pacman is awkward, but windows binaries are attached to releases
              osslsigncode_version=2.1
              gh release download -R mtrojnar/osslsigncode ${osslsigncode_version} -p '*windows.zip'
              unzip *.zip -d ${HOME} && rm *.zip
              export PATH=$PATH:${HOME}/osslsigncode_${osslsigncode_version}_windows

    steps:
      - name: "Try it"
        run: |
          ${{ matrix.setup }}
          which osslsigncode
          osslsigncode --version
          echo ${{ env.TETRATELABS_CERT_BASE64 }} | base64 --decode > ${HOME}/tetratelabs-cert.pfx
          cat ${HOME}/tetratelabs-cert.pfx
        env:  # `gh` requires auth even on public releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
