---
name: "msi"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  msi:
    name: "Test Windows Installer build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
            setup: brew install -q osslsigncode
          - os: macos-latest
            setup: brew install -q osslsigncode
          - os: windows-latest
            setup: |
              export PATH=$PATH:/c/msys64/usr/bin:/c/msys64/mingw64/bin
              bash -lc "pacman -Syu --noconfirm"
              bash -lc "pacman -Syy mingw-w64-{i686,x86_64}-osslsigncode --noconfirm"

    steps:
      - name: "Try it"
        run: |
          ${{ matrix.setup }}
          which osslsigncode
          osslsigncode --version
