---
name: "msi"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  msi:
    name: "Test Windows Installer build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
            # https://packages.ubuntu.com/focal/osslsigncode is old, but apt is less time than brew
            setup: |
              sudo apt update -qq && sudo apt install -qq -y osslsigncode
          - os: macos-latest
            setup: brew install -q osslsigncode
          - os: windows-latest
            setup: |  # windows binaries are attached to releases
              osslsigncode_version=2.1
              gh release download -R mtrojnar/osslsigncode ${osslsigncode_version} -p '*windows.zip'
              unzip *.zip -D /tmp && rm *.zip
              export PATH=$PATH:/tmp/osslsigncode_${osslsigncode_version}_windows

    steps:
      - name: "Try it"
        run: |
          ${{ matrix.setup }}
          which osslsigncode
          osslsigncode --version
        env:  # `gh` requires auth even on public releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}