---
name: "msi"

on:
  push:
    tags: ''
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  msi:
    name: "Test Windows Installer build (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # don't fail fast as sometimes failures are operating system specific
      matrix:
        include:
          - os: ubuntu-latest
            setup: |  # the osslsigncode package on ubuntu is out-of-date, but faster than homebrew
              sudo apt update -qq && sudo apt install -qq -y osslsigncode
          - os: macos-latest
            setup: brew install -q osslsigncode
          - os: windows-latest
            setup: |  # windows binaries are attached to releases
              osslsigncode_version=2.1
              GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh release download \
                -D /tmp -R mtrojnar/osslsigncode ${osslsigncode_version} -p '*windows.zip'
              unzip *.zip
              export PATH=$PATH:/tmp/osslsigncode_${osslsigncode_version}_windows

    steps:
      - name: "Try it"
        run: |
          ${{ matrix.setup }}
          which osslsigncode
          osslsigncode --version
